name: deploy to Eks
on: 
  push:
    branches:
      - 'master'
jobs:
  build:
    environment: uat-deployment
    name: tbc
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'

      # - name: build, tag, and push image to Amazon ECR
      #   env: 
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: Example-Voting-App
      #   run: |
      #     docker build -t $ECR_REGISTRY/result:$GITHUB_RUN_NUMBER -f ./result/Dockerfile
      #     docker push $REGISTRY/result:$GITHUB_RUN_NUMBER
      #     docker build -t $ECR_REGISTRY/vote:$GITHUB_RUN_NUMBER -f ./vote/Dockerfile
      #     docker push $REGISTRY/result:$GITHUB_RUN_NUMBER  
      #     docker build -t $ECR_REGISTRY/vote:$GITHUB_RUN_NUMBER -f ./worker/Dockerfile.j
      #     docker push $REGISTRY/result:$GITHUB_RUN_NUMBER                  
